#!/usr/bin/env python3
"""Default reflect harness — reads from Entire CLI + git, writes context to stdout."""

import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run(cmd, timeout=30):
    """Run a shell command and return stdout, or empty string on failure."""
    try:
        result = subprocess.run(
            cmd, shell=True, capture_output=True, text=True, timeout=timeout
        )
        return result.stdout.strip() if result.returncode == 0 else ""
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return ""


def has_entire():
    """Check if Entire CLI is available."""
    return bool(run("which entire"))


def has_git():
    """Check if we're in a git repo."""
    return bool(run("git rev-parse --is-inside-work-tree"))


def get_entire_checkpoints():
    """Get all checkpoints from Entire CLI."""
    raw = run("entire explain --short --search-all --no-pager")
    if not raw:
        return []

    checkpoints = []
    lines = raw.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        # Match checkpoint line: [id] "intent..."
        match = re.match(r'^\[([a-f0-9-]+)\]\s+(?:\[temporary\]\s+)?"(.+)"', line)
        if match:
            cp_id = match.group(1)
            intent = match.group(2).rstrip('"').replace("\\n", " ")
            # Next line(s) have date + commit info
            commits = []
            dates = []
            i += 1
            while i < len(lines) and lines[i].startswith("  "):
                commit_match = re.match(
                    r"^\s+(\d{2}-\d{2})\s+(\d{2}:\d{2})?\s*\(([a-f0-9]+)\)\s+(.*)",
                    lines[i],
                )
                if commit_match:
                    date_str = commit_match.group(1)
                    sha = commit_match.group(3)
                    msg = commit_match.group(4).strip()
                    commits.append({"sha": sha, "message": msg})
                    dates.append(date_str)
                i += 1
            checkpoints.append(
                {
                    "id": cp_id,
                    "intent": intent[:200],
                    "date": dates[0] if dates else "",
                    "commits": commits,
                }
            )
        else:
            i += 1

    return checkpoints


def get_entire_transcript(checkpoint_id, max_lines=100):
    """Get full transcript for a checkpoint, truncated."""
    raw = run(
        f"entire explain --checkpoint {checkpoint_id} --full --no-pager", timeout=15
    )
    if not raw:
        return ""
    lines = raw.split("\n")
    return "\n".join(lines[:max_lines])


def get_git_log(count=15):
    """Get recent git commits."""
    raw = run(f'git log --oneline -{count} --format="%h %ad %s" --date=short')
    if not raw:
        return []
    commits = []
    for line in raw.split("\n"):
        parts = line.split(" ", 2)
        if len(parts) >= 3:
            commits.append({"sha": parts[0], "date": parts[1], "message": parts[2]})
    return commits


def get_notes(notes_dir):
    """Read manual notes from .reflect/notes/."""
    notes = []
    if not notes_dir.exists():
        return notes
    for f in sorted(notes_dir.glob("*.md")):
        content = f.read_text().strip()
        if content:
            notes.append({"name": f.stem, "content": content})
    return notes


def get_last_run(reflect_dir):
    """Read .last_run state file."""
    last_run = reflect_dir / ".last_run"
    if not last_run.exists():
        return None
    try:
        return json.loads(last_run.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def write_last_run(reflect_dir, checkpoint_id, git_sha):
    """Write .last_run state file."""
    last_run = reflect_dir / ".last_run"
    state = {
        "last_checkpoint": checkpoint_id,
        "last_git_sha": git_sha,
        "timestamp": datetime.now().isoformat(),
    }
    last_run.write_text(json.dumps(state))


def generate_context(max_lines=150):
    """Generate context.md content from available evidence sources."""
    sections = []
    latest_checkpoint_id = None
    latest_git_sha = None

    # Header
    sections.append("# Dynamic Project Knowledge")
    sections.append(
        "<!-- GENERATED by reflect harness — do not edit, regenerate with: reflect context -->"
    )
    sections.append(
        f"<!-- Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M')} -->"
    )
    sections.append("")

    # Entire sessions
    if has_entire():
        checkpoints = get_entire_checkpoints()
        if checkpoints:
            latest_checkpoint_id = checkpoints[0]["id"]
            sections.append("## Recent Sessions")
            # Show last 5 sessions with intents
            for cp in checkpoints[:5]:
                date = cp["date"] or "unknown"
                intent = cp["intent"]
                commits_str = ""
                if cp["commits"]:
                    msgs = [c["message"][:80] for c in cp["commits"][:2]]
                    commits_str = f" → {'; '.join(msgs)}"
                sections.append(f"- **{date}** `{cp['id'][:12]}`: {intent}{commits_str}")
            sections.append("")

            # For the most recent session, include key transcript fragments
            if checkpoints:
                transcript = get_entire_transcript(checkpoints[0]["id"], max_lines=60)
                if transcript:
                    # Extract just the user/assistant exchanges, skip tool details
                    exchanges = []
                    for line in transcript.split("\n"):
                        if line.startswith("[User]") or line.startswith("[Assistant]"):
                            text = line.split("] ", 1)[-1][:150]
                            if text and not text.startswith("[Tool"):
                                exchanges.append(text)
                    if exchanges:
                        sections.append("## Latest Session Context")
                        for ex in exchanges[:8]:
                            sections.append(f"- {ex}")
                        sections.append("")

    # Git commits
    if has_git():
        commits = get_git_log(15)
        if commits:
            latest_git_sha = commits[0]["sha"]
            sections.append("## Recent Commits")
            for c in commits[:10]:
                sections.append(f"- `{c['sha']}` ({c['date']}) {c['message']}")
            sections.append("")

    # Manual notes
    reflect_dir = Path(".reflect")
    notes = get_notes(reflect_dir / "notes")
    if notes:
        sections.append("## Notes")
        for note in notes:
            sections.append(f"### {note['name']}")
            # Truncate long notes
            content_lines = note["content"].split("\n")
            for line in content_lines[:10]:
                sections.append(line)
            if len(content_lines) > 10:
                sections.append(f"_...({len(content_lines) - 10} more lines)_")
            sections.append("")

    # No evidence at all
    if len(sections) <= 4:
        sections.append("_No evidence sources found. Install Entire CLI for session capture, or make some git commits._")
        sections.append("")

    # Assemble and enforce line budget
    output = "\n".join(sections)
    lines = output.split("\n")
    if len(lines) > max_lines:
        lines = lines[:max_lines]
        lines.append(f"\n<!-- truncated at {max_lines} lines -->")
        output = "\n".join(lines)

    # Update .last_run
    if reflect_dir.exists():
        write_last_run(reflect_dir, latest_checkpoint_id, latest_git_sha)

    return output


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Default reflect harness")
    parser.add_argument(
        "--max-lines", type=int, default=150, help="Line budget for output"
    )
    parser.add_argument(
        "--format", choices=["md", "json"], default="md", help="Output format"
    )
    args = parser.parse_args()

    context = generate_context(max_lines=args.max_lines)

    if args.format == "json":
        print(json.dumps({"context": context}))
    else:
        print(context)


if __name__ == "__main__":
    main()
